"""AI-side schemas for the shared prototype contract.

The canonical domain entities in this file intentionally mirror the backend
contract. The LLM itself never creates canonical entity IDs or rule IDs.
Instead, the AI layer returns extraction candidates and the backend adapter
assigns canonical IDs and rule definitions before the data enters the shared
workflow.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class DomainModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Operator(str, Enum):
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    EQUAL = "EQUAL"
    STATUS_ACTIVE = "STATUS_ACTIVE"


class RequirementType(str, Enum):
    TURNOVER = "TURNOVER"
    GST = "GST"
    PAN = "PAN"
    UDYAM = "UDYAM"
    OEM_AUTHORIZATION = "OEM_AUTHORIZATION"
    OTHER = "OTHER"


class ComplianceStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    PENDING = "PENDING"
    UNVERIFIABLE = "UNVERIFIABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ExtractedRequirementCandidate(DomainModel):
    """Raw structured output expected from the LLM.

    Canonical IDs, source-document IDs, and rule IDs are intentionally not
    generated by the model. The caller/backend supplies those deterministically.
    """

    type: RequirementType
    title: str
    description: str
    operator: Operator
    threshold: float | int | None = None
    unit: str | None = None
    mandatory: bool
    source_page: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)


class TenderRequirement(DomainModel):
    """Canonical TenderRequirement shape used at the backend boundary."""

    id: str
    tender_id: str
    type: RequirementType
    title: str
    description: str
    operator: Operator
    threshold: float | int | None = None
    unit: str | None = None
    mandatory: bool
    source_document_id: str
    source_page: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)
    rule_id: str


class ExtractedField(DomainModel):
    """Canonical extracted-field shape shared with the backend."""

    id: str
    document_id: str
    field_name: str
    value: Any
    unit: str | None = None
    normalized_value: Any | None = None
    raw_text: str
    page: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)
    extraction_method: str


class ExtractedFieldCandidate(DomainModel):
    """Raw LLM output for one bidder-document field."""

    field_name: str
    value: Any
    unit: str | None = None
    normalized_value: Any | None = None
    raw_text: str
    page: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)


class ContradictionFinding(DomainModel):
    """A discrepancy between two extracted values.

    This is not a fraud finding and does not make a compliance decision.
    """

    finding_id: str
    field_name: str
    left_field_id: str
    right_field_id: str
    left_value: Any
    right_value: Any
    left_source_label: str
    right_source_label: str
    explanation: str
    requires_manual_review: bool = True


class ComplianceResultInput(DomainModel):
    """AI explanation input derived from the deterministic rule result.

    This is an adapter/read model, not a competing ComplianceResult entity.
    """

    requirement_title: str
    operator: Operator
    threshold: float | int | None
    unit: str | None
    actual: Any
    status: ComplianceStatus
    evidence_ids: list[str] = Field(default_factory=list)
    finding_ids: list[str] = Field(default_factory=list)
    verification_status: str | None = None
    verification_source_type: str | None = None
    verification_source_name: str | None = None
    verification_details: str | None = None
    declared_value: Any | None = None


class RequirementExtractionResult(DomainModel):
    """Envelope returned by the requirement extractor for one tender."""

    tender_id: str
    requirements: list[ExtractedRequirementCandidate]
    raw_model_output: str | None = None
